### ISSUE TITLE
Would the chip still behave as a Modchip after the flash?

### ISSUE THREAD

**Issue by andreacampanella** [Ryzee119/AladdinLCD#1]
One thing is quiet confusing is if the chip will retain it's ability to boot custom kernels after the update, if not, would be possible to mount it one the same bus with another modchip?

**Comment by Ryzee119** [comment]
From the readme:
It converts the modchip to a basic LCD driver, consequently it looses the ability to load a custom bios.

Yes, you could mount it on the same bus as an existing modchip I believe (although untested)
