### ISSUE TITLE
INPROPER LCD TEXT

### ISSUE THREAD

**Issue by benur75** [Ryzee119/AladdinLCD#3]
Good morning,

I have flashed yesterday evening using urjtag (mode  ft2232 with libsquirt programer). I had no problem. Then I installed everything, after tuning the contrast, I have text, but it is not correct, looks like the caracter code are not the good one. My LCD screen is a RG1602A, two lines. 

Could it be a compatibility problem with the lcd ?  Which lcd ref do you use ?

I have checked on XBMX, DVD2XBOX and Unleashed X, the probllem is the same.
On XBMC, the first line indicate: HBLBFbddldl* ($L
on the second line, it scrolls
bye

**Comment by benur75** [comment]
No problem, it was a weld issu. Please close. Bye

**Comment by benur75** [comment]
Thanks for you good job. If I can help you for something.
bye

**Comment by Ryzee119** [comment]
Resolved by user. Not an issue with repo
