### ISSUE TITLE
Pulsing VO

### ISSUE THREAD

**Issue by KiCadKid** [Ryzee119/AladdinLCD#5]
VO works normally when attached to 10k pot and 5v line. But when VO is connected from the chip, the contrast pulses. After checking voltages, VO seems to be fluctuating between 1 and 1.2v. Any idea?

**Comment by kenmoe** [comment]
scrolling text seems to be pulsating also even when VO has been stabilized with a pot.

**Comment by KiCadKid** [comment]
Solved
